### ISSUE TITLE
404 errors in Snowpack

### ISSUE THREAD

**Issue by ralphdas** [phantasmalmira/AngularSnowpackDemo#1]
First I tried replicating the setup manually only to encounter 404 errors on the app component.
``` [snowpack] [404] /app.component.css ```

After checking out the demo repository I found that I encountered the same errors. It seems that Snowpack is searching for the files directly in the 'src' directory without using the './src/app'. 

Same errors appear for the HTML file. I'll try to see if I can find the issue but any help is appreciated.

**Comment by ralphdas** [comment]
Found out that actually reloading snowpack  ``snowpack dev --reload`` and clearing the browser cache helped to get rid of the error

**Comment by phantasmalmira** [comment]
Yeah, `snowpack --reload` will fix it, it's because Snowpack processed the pre-ngcc @angular packages and doesn't detect an update despite there is a change in `node_modules` after ngcc processes them. As of now, Snowpack still doesn't provide an API for plugins to request a dependency re-install during dev mode yet.
